import { describe, it, expect } from 'vitest'

import { filterName } from './filterName'

describe('filterName', () => {
  it('Trim leading and trailing space', () => {
    expect(filterName(' pongsaphol     ')).toEqual('pongsaphol')

    expect(filterName(' s i a o r e o     ')).toEqual('s i a o r e o')
  })

  it('International language works fine', () => {
    const thai = 'พลเอก ประยุทธ์ จันทร์โอชา'
    expect(filterName(thai)).toEqual(thai)

    const chinese = '习近平' // generated by chatgpt
    expect(filterName(chinese)).toEqual(chinese)

    const jp = 'ラビットハウス'
    expect(filterName(jp)).toEqual(jp)
  })

  it('Normalize space', () => {
    expect(filterName('สวัสดี      ท่านสมาชิก')).toEqual('สวัสดี ท่านสมาชิก')

    expect(filterName('Hello\nWorld')).toEqual('Hello World')

    expect(filterName('ようこそ　おいで　ラビットハウス')).toEqual(
      'ようこそ おいで ラビットハウス'
    )

    expect(filterName('　　いち　　に　　さん　　')).toEqual('いち に さん')
  })

  it('Emoji', () => {
    const e1 = '❓❓❓'
    expect(filterName(e1)).toEqual(e1)

    const e2 = '👍🏿'
    expect(filterName(e2)).toEqual(e2)

    const e3 = '👍🏿 👍🏿 👍🏿 👍🏿👍🏿'
    expect(filterName(e3)).toEqual(e3)
  })

  it('Invisible characters', () => {
    const zeroWidth = 'สัน​​​​​​​​​​​​​​​​​โตะ'
    const normalStr = 'สันโตะ'

    expect(zeroWidth).not.toEqual(normalStr)
    expect(filterName(zeroWidth)).toEqual(normalStr)

    const testStr = 'ㅤㅤ ㅤㅤ'
    const expectedStr = ''
    expect(testStr).not.toEqual(expectedStr)
    expect(filterName(testStr)).toEqual(expectedStr)

    const หยุดเกียน = '⠀⠀⠀'
    const เลิกเกียน = ''
    expect(หยุดเกียน).not.toEqual(เลิกเกียน)
    expect(filterName(หยุดเกียน)).toEqual(เลิกเกียน)
  })

  it('Mixed case', () => {
    expect(filterName('　　　')).toEqual('')
    expect(filterName('   ')).toEqual('')

    expect(filterName('Icy เกียน  ❓')).toEqual('Icy เกียน ❓')

    const testStr = 'ㅤkingpin 2147483647'
    const expectedStr = 'kingpin 2147483647'
    expect(testStr).not.toEqual(expectedStr)
    expect(filterName(testStr)).toEqual(expectedStr)

    const testStr2 = '⠀gean⠀⠀ ⠀⠀'
    const expectedStr2 = 'gean'
    expect(testStr2).not.toEqual(expectedStr2)
    expect(filterName(testStr2)).toEqual(expectedStr2)
  })
})
